baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-artix"
themesdir = "../.."

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true



[markup]

defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokailight"
tabWidth = 4

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[params]
brand = "Artix"     # Brand of Site
subbrand = "Docs"   # Sub-Brand of Site, optional
ordersectionsby = "weight" # weight, title
alwaysTOC = true    # always have TOC for a page
alwaysBreadcrumb = true    # always have Breadcrumb for a page